//n(i)是偶数，则n(i+1)=n(i)/2,n(i)是奇数，则n(i+1)=3n(i)+1
//若n(i)=1则结束


#include<stdio.h>
unsigned long long iceNumber (unsigned long long n);
int main (void) {
  unsigned long long number;
  int count;
  while (scanf("%lld",&number) != EOF ) {
    printf("Hailstone generated by %lld:\n",number);
    count = 0;
    while (number != 1) {
      printf("%lld ",number);
      number = iceNumber(number);
      count ++;
    }
    printf("1\n");
    printf("Number of hailstone generated:%d\n\n",count+1);
  }
  return 0;
}

unsigned long long iceNumber (unsigned long long n) {
  if (n % 2 == 0) {
    return (n/2);
  } else {
    return (3*n + 1);
  }
}
